name: domain
description: Houses the domain-level entities, value objects and services.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
